// Copyright 2021 Prudnikov Nikolay. All Rights Reserved.

/*=============================================================================
	PrudnikovCommon.ush: Common
=============================================================================*/

#pragma once

#include "/Engine/Private/Common.ush"

#ifndef PR_SHADER_SL_INDIRECT
#define PR_SHADER_SL_INDIRECT 0
#endif

#ifndef PR_SHADER_LM_INDIRECT
#define PR_SHADER_LM_INDIRECT 0
#endif